### ISSUE TITLE
Problem with tic tac toy

### ISSUE THREAD

**Issue by freQuensy23-coder** [ptanmay143/py-console-games#1]
The problem when playing tic tac toe. When I try to put crosses in the place where it already stands, the program crashes
0 | X | 2 

O | 4 | 5 

6 | 7 | 8 

Enter the position where you want to play this round : 1
The position is already filled, try again!
Traceback (most recent call last):
  File "dumb-tic-tac-toe.py", line 141, in <module>
    Welcome()
  File "dumb-tic-tac-toe.py", line 14, in Welcome
    PlayGame()
  File "dumb-tic-tac-toe.py", line 28, in PlayGame
    availableChoices, plays = TurnUser(availableChoices, plays)
  File "dumb-tic-tac-toe.py", line 122, in TurnUser
    TurnUser()
TypeError: TurnUser() missing 2 required positional arguments: 'availableChoices' and 'plays'

**Comment by ptanmay143** [comment]
Did the pull request fix this issue? If not, please let me know and I will reopen this issue and investigate further.

**Comment by freQuensy23-coder** [comment]
No. everything is working.
